### ISSUE TITLE
enable ssh by default

### ISSUE THREAD

**Issue by ukscone** [PiSupply/iot-pi-gen#6]
Any chance you could enable ssh by default as i'm/i'll be running headless and it'd be handy to actually be able to get a shell to fix/edit things on occasion

**Comment by ryanteck** [comment]
This is a bit of a mixed one really. As most people will flash and leave it we don't want to distribute devices of SSH on default credentials. 

We could have it where it's an option to turn on in the control panel once the password is changed maybe? I have it on my to-do list for the password to be changable via it.

**Comment by ukscone** [comment]
should be able to do the ssh file in boot thing although it all depends if i remember or not so an option in the dashboard would be nice. as would changing the default raspbian password too

**Comment by ukscone** [comment]
basically sorted as raspi-config works for wifi setup now and can do  the ssh file thing too
