### ISSUE TITLE
have to setup wifi manually

### ISSUE THREAD

**Issue by ukscone** [PiSupply/iot-pi-gen#7]
raspi-config to setup the wifi doesn't work as it says unable to connect to wpa_supplicant. i have to do it manually creating my own wpa_supplicant.conf

**Comment by ryanteck** [comment]
Hmm, that is rather odd. I shall test this out tomorrow.

It *should* be a Raspbian Lite image with just our bits added so not sure why wpa_supplicant isn't in it. I'll test it out tomorrow or Monday to see.

**Comment by ukscone** [comment]
i'll admit i've not used raspbian lite much so don't know if there is a bug with raspi-config in it but wpa_supplicant is included so guessing probably just a transitory glitch

**Comment by ryanteck** [comment]
This should now be fixed in the latest image. I'll do some more testing before I confirm it has.

**Comment by ryanteck** [comment]
This seems to be fixed in the latest beta release.
